### ISSUE TITLE
Crash Immediately After Placing Infusion Pylon

### ISSUE THREAD

**Issue by HockeyZman2000** [jeremiahwinsley/pylons#1]
[crash-2021-11-10_13.47.30-server.txt](https://github.com/jeremiahwinsley/pylons/files/7515551/crash-2021-11-10_13.47.30-server.txt)

Just got this crash in my modpack, maybe you can look and see if it's your mod causing it?

**Comment by jeremiahwinsley** [comment]
I don't see the pylon mentioned in this crash log. It looks like Better End is trying to check for a "Blindness Resistance" attribute on a Quark stoneling and not finding that attribute.

```
Description: Ticking entity

java.lang.IllegalArgumentException: Can't find attribute betterendforge:blindness_resistance
```

```
-- Entity being ticked --
Details:
	Entity Type: quark:stoneling (vazkii.quark.content.mobs.entity.StonelingEntity)
	Entity ID: 3161
	Entity Name: Stoneling
	Entity's Exact location: -145.50, 20.00, 563.50
	Entity's Block location: World: (-146,20,563), Chunk: (at 14,1,3 in -10,35; contains blocks -160,0,560 to -145,255,575), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
```

**Comment by HockeyZman2000** [comment]
Oh my bad. It must have been a random crash because now I can't seem to reproduce it, weird. Thanks for the help!
