### ISSUE TITLE
Can't interact/break pylons

### ISSUE THREAD

**Issue by Nishh** [jeremiahwinsley/pylons#15]
Mod pack: ATM 8 (1.19.2)
pylons version: 1.19.2-3.1.0

There seems to be no errors, how do I debug this?

**Comment by jeremiahwinsley** [comment]
You can only break/interact with pylons placed by you, unless you're in creative.

**Comment by Nishh** [comment]
Can I disable that feature somehow? We are playing as a team (3-4 players) and we occasionally need to interact with each others farms.

**Comment by jeremiahwinsley** [comment]
I'm looking into adding FTB Teams support with a toggle to switch between player-only and team access. Let me know if this would work for your situation.

**Comment by Nishh** [comment]
That would be perfect. Thank you for your time and efforts.

**Comment by jeremiahwinsley** [comment]
Team support was released in 3.2.0 for 1.19/4.1.0 for 1.20.
