### ISSUE TITLE
Suggestion: check for if player's spawn is in same chunk as expulsion pylon to prevent griefing 

### ISSUE THREAD

**Issue by TheDyreBanana** [jeremiahwinsley/pylons#2]
Currently the expulsion pylon just sends people away no matter where their spawn is. However, if the pylon is placed in the same chunk as the player's spawn they are basically trapped until it is destroyed. Is there any way that the pylon could check where the player has their spawn set and send them to world spawn or just not send them away at all? Otherwise this could be used to permanently trap players inside their base or even at world spawn, especially if they aren't using beds to set their spawn.

**Comment by jeremiahwinsley** [comment]
What version are you on? It does check for both player spawn and world spawn, and should do nothing if they are within the spawn chunk. But I had to rewrite some of that code for 1.18 and I may have missed something.

**Comment by TheDyreBanana** [comment]
minecraft 1.18 atm7

**Comment by jeremiahwinsley** [comment]
Should be fixed in 2.0.1. Thanks for the report!
