### ISSUE TITLE
Harvest Pylon does not support harvesting Sourceberries

### ISSUE THREAD

**Issue by DerpyFrood0421** [jeremiahwinsley/pylons#20]
Not sure if this is a bug or intentional, but the pylon will not harvest sourceberries (from Ars Nouveau). It will harvest other crops without a problem, so it's not the way I have the pylon set up. Berries are planted on Rich Soil (from Farmer's Delight mod) but I get the same result when planted on farmland. 

Minecraft ver: 1.20.1
Modpack ver: All the Mods 9 v00.54
Forge ver: 47.1.3
Pylons ver: 4.0.0

**Comment by jeremiahwinsley** [comment]
Added support for sourceberries in 4.2.0.
