### ISSUE TITLE
Expulsion Pylon crash

### ISSUE THREAD

**Issue by User9684** [jeremiahwinsley/pylons#21]
Hi, I'm having an issue with the Expulsion Pylon.
This crash specifically is happening with conjunction with the FTBTeams mod on ATM9. 

From what I can personally tell, it seems like the crash happens if you left click an Expulsion Pylon owned by someone who is not inside an FTB team.

Error log: https://mclo.gs/iSkW8YH

**Comment by User9684** [comment]
UPDATE: I believe this error is caused by the `arePlayersInSameTeam` function not checking if either the owner or the player are in a team, so it's trying to check if `null` is equal to `team`, giving a NullPointerException.

**Comment by User9684** [comment]
UPDATE 2: even if both players HAVE a team, it still seems to crash the player who clicks it.

Crash log of another player who has the same error: https://mclo.gs/yA7D5fy

**Comment by jeremiahwinsley** [comment]
I think the problem is that I'm only checking the server team manager (which isn't present client side), and breaking blocks also tries to run that code on the client. Will verify in a bit.

**Comment by User9684** [comment]
> I think the problem is that I'm only checking the server team manager (which isn't present client side), and breaking blocks also tries to run that code on the client. Will verify in a bit.

Any update? And if so, when do you think it can be fixed?

**Comment by User9684** [comment]
Gracie!
