### ISSUE TITLE
[Suggestion] Add config option to extend duration of potion effect and number of seconds left before timer is reset.

### ISSUE THREAD

**Issue by AymenLoudiy** [jeremiahwinsley/pylons#22]
Some effects get canceled when the infusion pylon resets the potion effect, maybe adding that option in the config or making the effects permanent while infusion pylon is loaded would also be a solution.

**Comment by jeremiahwinsley** [comment]
Is this for the Ars Nouveau flight effect, or something else? I have gotten a couple requests to make flight work, I just submitted a PR to Ars Nouveau to add support for refreshing the effect: https://github.com/baileyholl/Ars-Nouveau/pull/1191

If it's another effect with a similar issue, I can look into that as well. Generally speaking this is a bug/compatibility issue with the effect, so I'd prefer to fix the effect if possible.

**Comment by AymenLoudiy** [comment]
It is the ars nouveau flight effect you are right.
Thank you for taking it into consideration.
