### ISSUE TITLE
Enhancement: Config for wider spawn protection from expulsion pylons

### ISSUE THREAD

**Issue by TheDyreBanana** [jeremiahwinsley/pylons#4]
Right now (afaik) only the spawn chunk is protected from expulsion pylons, would it be possible to add a chunk radius config option for preventing expulsion pylons from being placed?

**Comment by jeremiahwinsley** [comment]
Currently it prevents it from working anywhere in the spawn radius. So 16 blocks away from the world spawn by default, but configurable with `/gamerule spawnRadius`.

**Comment by TheDyreBanana** [comment]
well increasing spawn radius increases all protections, sometimes you just want it so people cant claim within 10 chunks of spawn but they can still get wood etc.

**Comment by jeremiahwinsley** [comment]
Added in 2.0.2.
