### ISSUE TITLE
Crash when trying to break a pylon with an annihilation plane from AE2 

### ISSUE THREAD

**Issue by TheDyreBanana** [jeremiahwinsley/pylons#5]
[crash-2021-12-10_20.34.43-server.txt](https://github.com/jeremiahwinsley/pylons/files/7696205/crash-2021-12-10_20.34.43-server.txt)
Hard crashes singleplayer client, and when I reloaded the world the pylon was gone. I am looking into other methods that could be used to destroy pylons as well. 
Edit: the pylon even goes into the AE system so you can steal a players pylon and then place it back down to claim their base.

**Comment by jeremiahwinsley** [comment]
The crash is from AE2, doesn't seem to be related to pylons.  However, AE2 seems to be ignoring the BlockBreak event that should prevent that. I'll see if there is a workaround for that.

**Comment by TheDyreBanana** [comment]
Should I forward the crash report to the AE2 github?

**Comment by TheDyreBanana** [comment]
Create can also break the pylons with its drill (doesn't even crash the game)

**Comment by TheDyreBanana** [comment]
When you wrote the fix for this did you write a check if the pylon isn't owned by a player? I just realized that if you set it to basically be unbreakable altogether and then write an exception for the owner of it, if the pylon has no owner only ops could break it. This is doable with AE2 formation planes and I believe create as well, so you could use this to grief and whatnot.

**Comment by jeremiahwinsley** [comment]
Good point, I've updated that to allow breaking pylons that don't have an owner.

**Comment by jeremiahwinsley** [comment]
Should be fixed in 2.0.4.
