### ISSUE TITLE
[1.18.1-2.0.6] infusionRequiredDuration config changes not taking effect properly

### ISSUE THREAD

**Issue by Salamance73** [jeremiahwinsley/pylons#8]
I changed the config option for the aforementioned setting from 3600 seconds to 60. The potion filter initially shows the correct time needed to charge it, but this is only before I actually start charging it. After I start charging it seemingly reverts back to the 3600 second default and will not allow me to use it in the infusion pylon when its over 60. 

Config change (shown in Configured GUI):
![image](https://user-images.githubusercontent.com/26430914/151111034-405cb8b7-9452-4840-b215-eb7d843a0800.png)

Pre-Charge:
![image](https://user-images.githubusercontent.com/26430914/151111088-5c244518-2918-4245-bf2d-b2e464a75470.png)

Post-Charge:
![image](https://user-images.githubusercontent.com/26430914/151111165-4960656f-4262-4718-8083-9e23a7403fa7.png)

**Comment by jeremiahwinsley** [comment]
It's not currently compatible with Configured, but should work if you edit the value in the config file with the pack closed. I'll look into making it work with Configured.

**Comment by Salamance73** [comment]
Ah, well I'm glad I mentioned Configured, thanks for the help!

**Comment by Salamance73** [comment]
I seemingly cannot get the config change to work even through normal config editing, along with that the config option appeared to be correctly formatted even before I did anything aside from the Configured change.

**Comment by jeremiahwinsley** [comment]
I have Configured working for single player, but it looks like I will need to switch to a server config, instead of a common config, to make this editable on a server.

**Comment by jeremiahwinsley** [comment]
This should be working on both client and server with version 2.0.7.
